name: Unit test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Create local.properties
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > local.properties

      - name: Run unit tests
        run: ./gradlew clean testDebugUnitTest